[api]
enabled = true
address = "[::]:8686"

[sources.vector_logs]
type = "internal_logs"

[sources.fly_log_metrics]
type = "internal_metrics"

[sources.nats]
type = "nats"
url = "nats://[${NETWORK-fdaa}::3]:4223"
queue = "${QUEUE-}"
subject = "${SUBJECT-logs.>}"
auth.strategy = "user_password"
auth.user_password.user = "${ORG-personal}"
auth.user_password.password = "${ACCESS_TOKEN?}"
connection_name = "Fly logs stream"


[sources.nats2]
type = "nats"
url = "nats://[${NETWORK2-fdaa}::3]:4223"
queue = "${QUEUE-}"
subject = "${SUBJECT-logs.>}"
auth.strategy = "user_password"
auth.user_password.user = "${ORG2-personal}"
auth.user_password.password = "${ACCESS_TOKEN2?}"
connection_name = "Fly logs stream2"

[transforms.log_json]
type = "remap"
inputs = ["nats","nats2"]
source = '''
# Parse JSON if needed
. = parse_json!(.message)
# Add timestamp if not present
if !exists(.timestamp) {
  .timestamp = now()
}
# Add lvl field from log.level
.lvl = .log.level
.a = .message
'''

[sinks.quickwit_logs]
type = "http"
method = "post"
inputs = ["log_json"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://quickwit-yral.internal:7280/api/v1/fly_nats_logs/ingest"
healthcheck.enabled = true


# [sinks.emit_syslog]
# inputs = ["log_json"]
# type = "console"
# encoding.codec = "text"

[sinks.console]
type = "console"
inputs = ["vector_logs"]
encoding.codec = "text"


[sources.http_logs]
type = "http_server"
address = "0.0.0.0:8685"

[transforms.http_log_json]
type = "remap"
inputs = ["http_logs"]
source = '''
# Parse JSON if needed
. = parse_json!(.message)
.a = .message
'''

[transforms.cf_log_json]
type = "filter"
inputs = ["http_log_json"]
condition = "exists(.app) && exists(.level) && exists(.message) && exists(.timestamp)"

[transforms.http_metrics]
type = "filter"
inputs = ["http_log_json"]
condition = "exists(.unix_timestamp_secs) && exists(.tag) && exists(.source) && exists(.metric)"

[transforms.split_metrics_list]
type = "remap"
inputs = ["http_metrics"]
source = '''
# Check if this is a metrics_list event
.source = .source
if .tag == "metrics_list" {
  # Create an array to hold the individual events
  events_list = []
  
  # Process each item in the metric array
  # log("SPLIT: Starting to process " + to_string(length(array!(.metric))) + " items", level: "info")
  for_each(array!(.metric)) -> |index, item| {
    # log("SPLIT: Processing item", level: "info")
    # Add the event to our events array
    item_obj = {
      "client_id": .source,
      "user_id": .tag,
      "events": [{
        "name": item.tag,
        "params": item.metric
      }]
    }
    events_list = push(events_list, item_obj)
  }
  
  # log("SPLIT: Finished processing items, created " + to_string(length(events)) + " events", level: "info")
  
  # Replace the current event with the array of individual events
  . = events_list
} else {
  # log("SPLIT: Regular event (not tides_turned_list), passing through", level: "info")

  . = [{
      "client_id": .source,
      "user_id": .user_id,
      "events": [{ 
        "name": .tag,
        "params": .metric
      }]
  }]
}
'''

[sinks.cf_quickwit_logs]
type = "http"
method = "post"
inputs = ["cf_log_json"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://quickwit-yral.internal:7280/api/v1/cf_logs/ingest"
healthcheck.enabled = true

# [sinks.quickwit_metrics]
# type = "http"
# method = "post"
# inputs = ["http_metrics"]
# encoding.codec = "json"
# framing.method = "newline_delimited"
# uri = "http://quickwit-yral.internal:7280/api/v1/metric_events/ingest"
# healthcheck.enabled = true

[sinks.ga4]
type = "http"
method = "post"
inputs = ["split_metrics_list"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "https://www.google-analytics.com/mp/collect?measurement_id=G-PLNNETMSLM&api_secret=${GA4_API_SECRET}"
batch.max_events = 1
