[api]
enabled = true
address = "[::]:8686"

[sources.vector_logs]
type = "internal_logs"

[sources.fly_log_metrics]
type = "internal_metrics"

[sources.nats]
type = "nats"
url = "nats://[${NETWORK-fdaa}::3]:4223"
queue = "${QUEUE-}"
subject = "${SUBJECT-logs.>}"
auth.strategy = "user_password"
auth.user_password.user = "${ORG-personal}"
auth.user_password.password = "${ACCESS_TOKEN?}"
connection_name = "Fly logs stream"

[transforms.log_json]
type = "remap"
inputs = ["nats"]
source = '''
# Parse JSON if needed
. = parse_json!(.message)
# Add timestamp if not present
if !exists(.timestamp) {
  .timestamp = now()
}
# Add lvl field from log.level
.lvl = .log.level
.a = .message
'''

[sinks.quickwit_logs]
type = "http"
method = "post"
inputs = ["log_json"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://quickwit-yral.internal:7280/api/v1/fly_nats_logs/ingest"
healthcheck.enabled = true


# [sinks.emit_syslog]
# inputs = ["log_json"]
# type = "console"
# encoding.codec = "text"

[sinks.console]
type = "console"
inputs = ["vector_logs"]
encoding.codec = "text"


[sources.http_logs]
type = "http_server"
address = "0.0.0.0:8685"

[transforms.http_log_json]
type = "remap"
inputs = ["http_logs"]
source = '''
# Parse JSON if needed
. = parse_json!(.message)
.a = .message
'''

[transforms.cf_log_json]
type = "filter"
inputs = ["http_log_json"]
condition = "exists(.app) && exists(.level) && exists(.message) && exists(.timestamp)"

[transforms.http_metrics]
type = "filter"
inputs = ["http_log_json"]
condition = "exists(.unix_timestamp_secs) && exists(.tag) && exists(.source) && exists(.metric)"

[sinks.cf_quickwit_logs]
type = "http"
method = "post"
inputs = ["cf_log_json"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://quickwit-yral.internal:7280/api/v1/cf_logs/ingest"
healthcheck.enabled = true

[sinks.quickwit_metrics]
type = "http"
method = "post"
inputs = ["http_metrics"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://quickwit-yral.internal:7280/api/v1/metric_events/ingest"
healthcheck.enabled = true
