
app = "quickwit-yral"
primary_region = "bom"

[build]


[[services]]
internal_port = 7280
protocol = "tcp"
min_machines_running = 1

[[services.ports]]
handlers = ["tls"]
port = 443

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 8

[mounts]
source = "quickwit_data"
destination = "/quickwit/qwdata"
initial_size = "10gb"

[metrics]
port = 9090
path = "/metrics"
