
app = "quickwit-yral"
primary_region = "bom"

[build]


[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 8

[mounts]
source = "quickwit_data"
destination = "/quickwit/qwdata"
initial_size = "10gb"

[metrics]
port = 9090
path = "/metrics"
