
app = "quickwit-yral"
primary_region = "bom"

[build]


[http_service]
internal_port = 7280
force_https = false
min_machines_running = 1

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2

[mounts]
source = "quickwit_data"
destination = "/quickwit/qwdata"
initial_size = "10gb"

[metrics]
port = 9090
path = "/metrics"
