app = 'grafana-yral'
primary_region = 'ams'

[build]
image = 'grafana/grafana-oss'

[[mounts]]
source = 'grafana-yral'
destination = '/var/lib/grafana'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
GF_INSTALL_PLUGINS = "grafana-bigquery-datasource,quickwit-quickwit-datasource"
GF_SERVER_ROOT_URL = "https://grafana-yral.fly.dev/"
